version: "3"
services:
  poke_flask:
    container_name: poke_flask_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    links:
      - poke_db
    depends_on:
      - poke_db
  poke_db:
    container_name: poke_db_container
    build:
      context: ./database/
      dockerfile: Dockerfile_db
    ports:
      - "5432:5432"
