swagger: "2.0"
info:
  version: "1.0.0"
  title: "Pokemon DB API"
basePath: "/specs"
tags:
  - name: "pokemon"
schemes:
  - "https"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /poke_db/{pokemon_name}:
    get:
      tags:
        - "pokemon"
      summary: "Get a pokemon from the DB"
      operationId: "query_by_name"
      parameters:
        - name: "pokemon_name"
          in: "path"
          description: "The name of the pokemon to retrieve"
          required: true
          type: "string"
      responses:
        200:
          description: "Successfully retrived pet, returns pokemon json"
          schema:
            $ref: "#/definitions/Pokemon"
        404:
          description: "Requested DB query by name NOT found"

  /api_fetch/{value}:
    put:
      tags:
        - "pokemon"
      summary: "Add new pokemon to the Database"
      operationId: "insert_poke_into_db"
      parameters:
        - name: "value"
          description: "The id or name of the pokemon to update from the api"
          in: "path"
          type: "string"
          required: true
      responses:
        200:
          description: "Successfully added pokemon, returns pokemon json"
        418:
          description: "Im a teapot, already present in db"
definitions:
  Pokemon:
    type: "object"
    required:
      - "id"
      - "name"
      - "jsos_sting"
    properties:
      id:
        type: "integer"
        format: "string"
      name:
        type: "string"
      json_string:
        type: "string"
        format: "JSON"
    example:
      id: 1
      name: "balbasaur"
      json_string: {id: 1, name: "balubasaur", etc: {{}}}

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
